### PR TITLE
fixing null and undefined lookup

### PR DESCRIPTION
**Pull request by dasilvacontin**
Issue #397.

### CODE REVIEW

**Comment by dasilvacontin** [comment]
Regarding backwards compatibility, what are your thoughts, @phillipj, @janl?

IMO, this could be considered a bugfix/patch, that might even help someone notice tests that should be failing.

**Comment by phillipj** [comment]
Although I completely agree that this should be considered a bugfix, its a change which might cause  unexpected behavior in many projects. Being very explicit about this change for those developers upgrading to v2.0 would hopefully save many hours of debugging.

I really appreciate good changelogs / upgrade guides when libraries do breaking changes. Could that be an idea for the v2.0 release?

**Comment by janl** [comment]
Even if an issue fixes a bug, if it breaks BC, it breaks BC and should be treated as such (carefully, major version bump).

Good upgrade guides are important too.

I’m a fan of small-scope major version releases, so it is easy to upgrade (like hapi generally does).

Major version numbers are cheap.

**Comment by dasilvacontin** [comment]
True, sorry for missing that. Thanks guys! It is more likely to change behaviour in unexpected ways in lots of projects, than helping to discover old bugs.

I label this PR as v2.

**Comment by dasilvacontin** [comment]
Heh, I love edge cases. Not only the `if` was unreadable, but it was failing with this edge case:

```javascript
> view = { shares: { fb: 5 }, kipos: { shares: { fb: undefined } } }
> Mustache.render("{{#kipos}}{{shares.fb}}{{/kipos}}", view)
'5'
```
This is due to `context.view.hasOwnProperty(name)` failing when using dot notation.

**Comment by dasilvacontin** [comment]
I've refactored the if using a new variable, `lookupHit`. Can you guys please take a look and give feedback? :)

**Comment by phillipj** [comment]
Once again, awesome tests! LGTM

**Comment by dasilvacontin** [comment]
Thanks! I'll mark this as `TO-MERGE` and `v2.0`. Coming soon.

**Pull request merged**
