### PR TITLE
Created command line tool

### PR DESCRIPTION
**Pull request by phillipj**
Hey,

my first shot at a CLI used to render a mustache template with a data view and writes the template into stdout when successfull. Otherwise meaningfull errors into stderr.

The short story is it enables
```bash
$ mustache myTemplate.mustache dataView.json > output.html
```
Changes in the readme.md + tests pretty much sums it up.

Any thoughts?

### CODE REVIEW

**Comment by bobthecow** [comment]
I'd follow the ruby mustache argument order: `mustache [data] [template]`

(see [mustache(1)](http://mustache.github.io/mustache.1.html))

**Comment by bobthecow** [comment]
Also, we should allow users to specify `-` as the data or template argument, which would grab stdin.

```bash
cat data.json | mustache - myTemplate.mustache > out.html
```

**Comment by dasilvacontin** [comment]
Awesome! With @bobthecow's changes, I'd give :+1:. Can't wait to have this, since I recently started toying with using `package.json`'s scripts as my 'task-runner'.

**Comment by bobthecow** [comment]
While we're at it, how 'bout allowing an arbitrary number of datas?  `mustache <data> [<data> ...] <template>`

**Comment by dasilvacontin** [comment]
@bobthecow, what would be the purpose of input? What's the expected output?

**Comment by bobthecow** [comment]
@dasilvacontin `(Mustache.render(tpl, data) for data in datas).join("\n")`

**Comment by dasilvacontin** [comment]
I see, interesting! Thumbs up incoming after the commits. :)

**Comment by phillipj** [comment]
Great feedback guys, thanks! I'll do some changes within the next couple of days :)

**Comment by phillipj** [comment]
Has changed argument ordering and added support for stdin.

**Comment by phillipj** [comment]
@bobthecow multiple data views are interesting! Have you thought of scenarios where multiple data views would enable something one data view with an array as root could not? 

E.g two views of:
```json
{
	"message": "LeBron"
}
```
```json
{
	"message": "r0x!"
}
```
compared to one view with:
```json
[
	{
		"message": "LeBron"
	},
	{
		"message": "r0x!"
	}
]
```

**Comment by bobthecow** [comment]
I was thinking of a use case of a directory full of data files, and not having to preprocess them into a JSON array before using them. `mustache messages/*.json message.mustache > messages.html`

But I suppose you'd usually want to do more than newline delimited, so you're back to preprocessing.

**Comment by phillipj** [comment]
Played with that thought for a couple of minutes. Looks like it would be possible to push multiple single JSON objects into stdin reading them with the awesome [JSONStream](https://github.com/dominictarr/JSONStream) module.
```bash
$ cat messages/*.json | mustache - message.mustache > messages.html
```
Knowing its possible is good and all, but it doesnt really sound like you need it atm? If not lets do a PR on it later if/when someone actually needs it, I would happily contribute.

**Comment by bobthecow** [comment]
Don't hold anything up for my hypothetical feature. :shipit: :)

**Comment by bobthecow** [comment]
jsonstream is pretty cool. i've played with it a bit as well :)

**Comment by dasilvacontin** [comment]
Cool!

**Comment by bobthecow** [comment]
:+1:

**Pull request merged**
