### PR TITLE
Simplify multiple statements to a single line return statement

### PR DESCRIPTION
**Pull request by harryi3t**
I took [this PR](https://github.com/janl/mustache.js/pull/551)
and modified it to make it work.

Ran the test cases before pushing. All passed

### CODE REVIEW

**Comment by harryi3t** [comment]
hey @phillipj,
could you look into this. Should I be pushing only one commit?

**Comment by phillipj** [comment]
Thanks, I'll have a look as soon as I've got some spare time.

Please squash the commits, especially since the first commit introduces
syntax errors IIRC.

**Comment by dasilvacontin** [comment]
Let me check if these changes provoke any edge case...

**Comment by dasilvacontin** [comment]
I believe these changes introduces incorrect behaviour, but I'm waiting to confirm so: #553.

**Comment by dasilvacontin** [comment]
I don't really think we can simplify these lines, unless we want to provide a different rendering behaviour for values different than `undefined` and `null`. And the result wouldn't be simpler or less lines of code. :smile:

**Pull request closed without merging**
