### PR TITLE
Minimal support for component(1)

### PR DESCRIPTION
**Pull request by jmas**
Added support for component(1): https://github.com/component

### CODE REVIEW

**Comment by dasilvacontin** [comment]
ping @jmas

**Comment by jmas** [comment]
Hello, I think it is not actualy now.

On 22 March 2015 at 03:22, David da Silva Contín <notifications@github.com>
wrote:

> ping @jmas <https://github.com/jmas>
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/janl/mustache.js/pull/393#issuecomment-84490576>.
>



-- 
Mobile: +38 099 669 15 06

**Comment by dasilvacontin** [comment]
@jmas, I didn't understand what you mean there. :/

**Comment by jmas** [comment]
@dasilvacontin Sorry for not informative comment. This "component(1) support" is not actual for me now because I started use another tool. It seems people not interest to use this future. So you can drop this pull request.

**Comment by dasilvacontin** [comment]
You meant useful, right? Okay, I close the PR. Thanks for the follow up!

**Pull request closed without merging**
