### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by dasilvacontin** [comment]
LGTM, thanks for the link too!

**Comment by kkirsche** [comment]
Yep. Also just an FYI there are discussions to move bower to NPM anyway so I wouldn't really plan to support it for ever: bower/bower#1520

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it in case people bug you about removing it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Comment by dasilvacontin** [comment]
Thanks for the additional info. I don't need bower myself, nor I'm a fan/user.

**Pull request merged**
