### PR TITLE
an image is wroth a thousand words

### PR DESCRIPTION
**Pull request by videlalvaro**

### CODE REVIEW

**Comment by phillipj** [comment]
@videlalvaro it looks like the awesome image has disappeared :( Do you have a copy by any chance?

**Comment by videlalvaro** [comment]
No :(

**Comment by Andersos** [comment]
Is this the image? I still see it.

687474703a2f2f64323477366273726862656839642e636c6f756466726f6e742e6e65742f70686f746f2f615a504e476f6e5f34363073612e676966

**Comment by videlalvaro** [comment]
yup, that's the image, but I don't see the one linked by @phillipj

**Comment by dasilvacontin** [comment]
Image back thanks to https://github.com/janl/mustache.js/pull/471.

**Pull request merged**
