### PR TITLE
Fixes #429 - support .js views with functions.

### LINKED ISSUE #429: Mustache.js template with function fails using command line tool
Using the examples from the readme section, I get the following exception when trying it with the command line tool (installed with npm):
```
undefined:3
	"bold": function () {
	         ^
SyntaxError: Unexpected token u
    at Object.parse (native)
    at /usr/local/lib/node_modules/mustache/bin/mustache:49:13
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/mustache/bin/mustache:72:5)
    at ReadStream.g (events.js:180:16)
    at ReadStream.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```
View
```
{
	"name": "Tater",
	"bold": function () {
		return function (text, render) {
			return "<b>" + render(text) + "</b>";
		}
	}
}
```
Template
```
{{#bold}}Hi {{name}}.{{/bold}}
```
When trying the same within the browser it works. What am I missing?

Background: I want to build a HTML template generator using the command line tool.

### PR DESCRIPTION
**Pull request by JEStaubach**
Allows functions to be passed in views by allowing javascript files instead of only JSON files.

### CODE REVIEW

**Comment by phillipj** [comment]
Thanks a lot for this contribution! 💯 

Any plans or thoughts for testing this? It's important we know this works as expected, both currently and going forward when doing future improvements.

**Comment by JEStaubach** [comment]
I should be able to make that happen. Since #429 referenced having an issue with the bold example in the readme section that sounds like a good test to start with.

**Comment by phillipj** [comment]
Published in v3.1.0.

**Comment by ph1-xyz** [comment]
> Allows functions to be passed in views by allowing javascript files instead of only JSON files.

Hi @JEStaubach!
I'm a newcomer to mustache and to development in general. Can you explain me this can be done? 

Thanks!!

**Pull request merged**
