### PR TITLE
Add partials support to cli

### PR DESCRIPTION
**Pull request by palkan**
Added partials support to CLI.

Usage:

```sh
mustache data.json template.mustache -p path/to/partial.mustache -p path/to/partial2.mustache
```

### CODE REVIEW

**Comment by phillipj** [comment]
This looks amazing! :+1:

A couple of things comes to mind:
- Document this in help / syntax hint?
- Optional args are usually *before* required args in CLI tools?

**Comment by palkan** [comment]
Ok, I've added some documentation and updated CLI to not depend on args order.

**Comment by mattecapu** [comment]
This fixes issue #483

**Comment by phillipj** [comment]
Could you squash your commits? Other than that it LGTM to me.

**Comment by palkan** [comment]
Done.

**Comment by phillipj** [comment]
Thanks! Lets poke @dasilvacontin and ask for a minor release for this :dancers:

**Comment by dasilvacontin** [comment]
Thanks for the contribution! Alright, let me see if I can publish a minor quickly..

**Comment by dasilvacontin** [comment]
Done!

**Pull request merged**
