### PR TITLE
Refactor Writer.renderTokens() for better readability.

### PR DESCRIPTION
**Pull request by phillipj**
Hi,

PR for #411. It splits the old Writer.renderTokens() into several small functions with a single responsible.
Also removed a lengthy case-switch which quickly gets error prone.

Any thoughts?

### CODE REVIEW

**Comment by phillipj** [comment]
Seems the alternative case-switch added a measurable performance hit :( I'll see what I can do with it.

**Comment by dasilvacontin** [comment]
Keep us updated!, and thanks for the work! :)

**Comment by dasilvacontin** [comment]
Any update @phillipj?

**Comment by phillipj** [comment]
Sorry @dasilvacontin, forgot to push some local changes.. By doing a more similar if-else style comparable to the old switch-style, the performance penalty disappeared.

Would you considered it different enough to see any value in this refactoring?

**Comment by dasilvacontin** [comment]
No worries, I was just curious! :) It definitely looks cleaner. I will take a better look tonight!

**Comment by dasilvacontin** [comment]
:+1:

**Comment by dasilvacontin** [comment]
Oups, commits were not squashed.  I have to be extra-careful about that next time.

**Pull request merged**
