### PR TITLE
Preserve indentation when rendering partials

### PR DESCRIPTION
**Pull request by yotammadem**
A fix for: https://github.com/janl/mustache.js/issues/562

### CODE REVIEW

**Comment by yotammadem** [comment]
not all spec tests are passing, closing...

**Comment by yotammadem** [comment]
I've added all the tests described in this spec: https://github.com/mustache/spec/blob/master/specs/partials.yml
And they are passing now

**Comment by yotammadem** [comment]
I decided to follow the original solution of @kevindew (PR: https://github.com/janl/mustache.js/pull/613) as it looks more elegant
I had to change some minor things to make it work according the the spec tests

**Comment by phillipj** [comment]
This looks really promising! Adding the tests from the mustache spec project was a great addition 👍 

I really feel @kevindew should get more credit for his contributions, as he wrote the first draft in #613 as you mention. At the moment, none of the commits has his name on it, which isn't quite fair in my eyes. Wondering if we should use his changes as the first commit, then add your commits as tweaks on top. That way you both get credit for your contributions, well deserved 😄

**Comment by yotammadem** [comment]
@phillipj 
Sorry,
I didn't think about the commits/credit aspect, I just wanted the thing to work.
I will re-arrange the PR such that it will include Kevin's commits

**Comment by phillipj** [comment]
Fully understandable!

Cool 👍

**Comment by yotammadem** [comment]
Done - please look at 
https://github.com/janl/mustache.js/pull/705

**Pull request closed without merging**
