### PR TITLE
Fix indentation of inline partials (issue #715)

### PR DESCRIPTION
**Pull request by yotammadem**

### CODE REVIEW

**Comment by phillipj** [comment]
Cool, I'll have a look as soon as I -- hopefully before the weekend.

**Comment by phillipj** [comment]
Interesting solution indeed!

Thinking out loud, my first hope was that we could fix this in a very isolated part of the source code, instead of involving several functions and new kinds of data/tokens being created. E.g. only in the `Writer.prototype.indentPartial()` function would have been ideal, as that function sounds very much in charge for indentation of partials.. Might be easier said than done though.

Thanks a lot for your quick response. I'll dive in as well to see if we end up with the same solution or maybe a combination of both.

**Comment by yotammadem** [comment]
I agree. I tired to find the quickest solution that satisfies our requirements. It emphasises the complexity of having too much coupling between the parse function and the indentPartials function like you said. I will try to figure out a better way, now that we have all tests in place, it should be easy to verify the solution.

**Comment by phillipj** [comment]
Thanks a lot for finding a fix to this indentation bug! 👍

**Comment by phillipj** [comment]
Published in v3.1.0.

**Pull request merged**
