### PR TITLE
Indent Partials

### PR DESCRIPTION
**Pull request by kevindew**
As referenced in this issue: https://github.com/janl/mustache.js/issues/562

Partials aren't indented as per the spec: https://github.com/mustache/spec/blob/master/specs/partials.yml#L13-L15

This adds indentation tracking for partials and applies them to the first instance of a partial on a line (to not indent inline partials which would violate a different part of the spec).

It's not really a perfect implementation - to really sort this would require reproaching how tokenising is done, so this sort of slots around the current approach to that.

### CODE REVIEW

**Comment by brettstack** [comment]
Any update?

**Comment by dasilvacontin** [comment]
Nope, all updates are in the respective Issues / PRs. We lack maintainer force. Any help reviewing issues / PRs is appreciated! :)

**Comment by aayalam** [comment]
Is it possible to receive the indentation string within the called template?

I read the indentation of the first line is part of the specs, but It would be a reasonable solution to merely remove the indentation of the first partial's line and delegating this task to the called template; doing this way, the developer could decide to apply (or not) the indentation as needed.

**Comment by phillipj** [comment]
These changes with some additions was merged in https://github.com/janl/mustache.js/pull/705, therefore closing this PR.

Thanks for your contribution 💯

**Pull request closed without merging**
