### PR TITLE
Clarifies and improves language in documentation

### PR DESCRIPTION
**Pull request by jfmercer**
* Although my previous PR (#469) on this topic was merged, it caused
[quite a discussion](https://github.com/janl/mustache.js/pull/469) about
the clarity of the language I wrote.
* This commit seeks to clarify and improve the sentence under discussion.
* Documentation should be as clear, precise, and unambiguous as possible. 
Because I cannot know how a reader interprets my writing, I depend on 
feedback to understand the quality of my prose. Therefore, suggestions 
and conversation are welcome.

### CODE REVIEW

**Comment by jfmercer** [comment]
This PR seeks to improve the documentation based on the conversation about PR #469.

**Comment by bobthecow** [comment]
:+1::+1:

Much clearer, thank you.

**Comment by dasilvacontin** [comment]
Thanks! LGTM

**Comment by Romanx** [comment]
Yeah :+1: from me too. Much clearer.

**Comment by dasilvacontin** [comment]
Alright, merging this one in, thanks @jfmercer and people who participated in the discussion! :)

**Pull request merged**
